### ISSUE TITLE
誤字報告など

### ISSUE THREAD

**Issue by purple-jwl** [SCCP2016/rubytutorial-for-sccp2016#5]
@ababup1192 さんの紹介でこの資料を読んでみました。

誤字報告などはIssuesにとのことだったのでこちらに書きます。

細かいことですが修正が必要そうな箇所を挙げておきますので、ご確認お願いします。
(ざっと読んだだけなので見逃しているところがあるかもしれないです。)
(ほとんど見出し番号についてです。)
- [ ] 「第1章 導入 (目次)」に見出し番号を振っていない
- [ ] 「第1章 色々な型」の見出し番号が異なる
- [ ] 「第2章 制御式 (目次)」に見出し番号を振っていない
- [ ] 「第3章」の見出し番号が全て異なる
- [ ] 「第6章 特異メソッド」に見出し番号を振っていない
- [ ] 「第7章 モジュール (目次)」に「色々なモジュール」が記載されていない
- [ ] 「第8章 Bundlerからツールを使う」に見出し番号を振っていない
- [ ] 「第9章 入出力 (目次)」で適切に改行されていない

以上です。

内容については分かりやすくて良かったです 👏

**Comment by misoton665** [comment]
@purple-jwl 
ご指摘頂き、ありがとうございます！
内容に関しても何かあれば何でもissueやPR投げてくださいね。
